### PR TITLE
Added initial CubeConversion interface

### PR DESCRIPTION
**Pull request by philippjfr**
Adds an initial `CubeConversion` interface allowing cubes to be easily converted to HoloViews and HoloCube Element types. The conversion will automatically infer whether the data is geographic (i.e. has latitude and longitude axes) and use the appropriate Element type to plot the data. Here's a simple example using the conversion interface:

``` python
import iris
import iris.coords

def realization_metadata(cube, field, fname):
    if not cube.coords('realization'):
        realization_number = fname[-6:-3]
        realization_coord = iris.coords.AuxCoord(np.int32(realization_number),
                                                 'realization')
        cube.add_aux_coord(realization_coord)

surface_temp = iris.load_cube(iris.sample_data_path('GloSea4', 'ensemble_???.pp'),
              iris.Constraint('surface_temperature', realization=lambda value: True),
              callback=realization_metadata)

import holoviews as hv
import holocube as hc

hv.notebook_extension()

hc.Cube(surface_temp).to.image(['longitude', 'latitude'])
```

screen shot 2016-03-15 at 4 11 17 pm

The HoloCube object wraps the cube and using the `.to` interface we can convert the multi-dimensional cube to individual Image Elements. The cube conversion interface automatically infers the value dimension and any remaining dimensions which translate into sliders to explore the data.

### CODE REVIEW

**Comment by philippjfr** [comment]
Ready to review and merge. This only adds the initial interface, I've already got another PR building on this one refactoring the cube module.

**Comment by jlstevens** [comment]
Looks good to me. 

My only question is why you chose to use inline imports for the elements? Don't we expect the elements in geo to be available or are there cyclic import issues?

**Comment by philippjfr** [comment]
Yes, due to cyclic import issues. The Elements you're converting to are potentially subclasses of HoloCube, but you're right that the regular Elements can simply be imported normally. An alternative would be to move the conversion interface to the element module and then inline the `CubeConversion` in the `to` method.

**Comment by marqh** [comment]
this looks grand, thank you @philippjfr

**Pull request merged**
